# ==============================================================================
# CI/CD PIPELINE - Déploiement automatique sur Vercel
# ==============================================================================

name: Deploy to Vercel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  # Job 1: Tests et Build
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 📦 Install dependencies
        run: npm ci
      
      - name: 🔍 Lint code
        run: npm run lint
      
      - name: 🏗️ Build application
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_API_VERSION: ${{ secrets.NEXT_PUBLIC_API_VERSION }}
      
      - name: ✅ Build successful
        run: echo "✅ Build terminé avec succès"

  # Job 2: Déploiement Preview (Pull Requests)
  deploy-preview:
    needs: test-and-build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 📦 Install Vercel CLI
        run: npm install -g vercel@latest
      
      - name: 🔄 Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 🏗️ Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 🚀 Deploy Preview to Vercel
        id: deploy
        run: |
          URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=$URL" >> $GITHUB_OUTPUT
      
      - name: 💬 Comment PR with Preview URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Preview déployé !**\n\n🔗 URL: ${{ steps.deploy.outputs.preview_url }}'
            })

  # Job 3: Déploiement Production (main branch)
  deploy-production:
    needs: test-and-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 📦 Install Vercel CLI
        run: npm install -g vercel@latest
      
      - name: 🔄 Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 🏗️ Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 🚀 Deploy to Production
        id: deploy
        run: |
          URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "production_url=$URL" >> $GITHUB_OUTPUT
      
      - name: ✅ Deployment successful
        run: |
          echo "🎉 Déploiement en production réussi !"
          echo "🔗 URL: ${{ steps.deploy.outputs.production_url }}"
      
      - name: 📊 Create deployment summary
        run: |
          echo "## 🚀 Déploiement Production" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Status:** Déployé avec succès" >> $GITHUB_STEP_SUMMARY
          echo "🔗 **URL:** ${{ steps.deploy.outputs.production_url }}" >> $GITHUB_STEP_SUMMARY
          echo "📅 **Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "👤 **Auteur:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "📝 **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY

  # Job 4: Notifications (optionnel)
  notify:
    needs: [deploy-production]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: 📧 Send notification
        run: |
          if [ "${{ needs.deploy-production.result }}" == "success" ]; then
            echo "✅ Notification: Déploiement réussi"
          else
            echo "❌ Notification: Déploiement échoué"
          fi
